# GitHub Issue Form: Task template
name: "Task"
description: "Create a task with status, priority, assignee, labels, linked issues, attachments, and a user story."
title: "[TASK] {{task_title}}"
labels:
  - "task"
body:
  - type: markdown
    attributes:
      value: |
        Use this form to create a task. You can attach files or screenshots by dragging them into the "Description and attachments" field below.
  - type: input
    id: task_title
    attributes:
      label: "Task title"
      description: "Short, descriptive title for the task"
      placeholder: "e.g., Implement user login"
      required: true
  - type: dropdown
    id: status
    attributes:
      label: "Status"
      description: "Current status of the task"
      options:
        - "To do"
        - "In progress"
        - "In review"
        - "Done"
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Select the priority"
      options:
        - "P0 (Critical)"
        - "P1 (High)"
        - "P2 (Medium)"
        - "P3 (Low)"
      required: true
  - type: checkboxes
    id: labels
    attributes:
      label: "Labels"
      description: "Select relevant labels (frontend/backend/bug/feature/documentation)"
      options:
        - "frontend"
        - "backend"
        - "bug"
        - "feature"
        - "testing"
        - "documentation"
  - type: users
    id: assignees
    attributes:
      label: "Assignee"
      description: "Select one or more GitHub users to assign"
  - type: input
    id: linked_issues
    attributes:
      label: "Linked issues / Dependencies"
      description: "Mention other issues that must be completed first or are related. Example: Depends on: #12 (User login implementation)"
      placeholder: "Depends on: #12"
  - type: textarea
    id: user_story
    attributes:
      label: "User Story"
      description: "Describe the user story this task implements (As a ..., I want ..., so that ...)"
      placeholder: "As a user, I want ... so that ..."
  - type: dropdown
    id: sprint
    attributes:
      label: "Sprint"
      description: "Select which sprint this task belongs to"
      options:
        - "Sprint 1"
        - "Sprint 2"
        - "Sprint 3"
        - "Sprint 4"
        - "Backlog"        
  - type: input
    id: due_date
    attributes:
      label: "Due Date (optional)"
      description: "Enter due date or milestone if known"
      placeholder: "e.g., 2025-11-15"
  - type: textarea
    id: description
    attributes:
      label: "Description and attachments"
      description: "Detailed description, steps, acceptance criteria, logs, screenshots, or other files (drag & drop files here to attach)."
      placeholder: "Detailed description, acceptance criteria, and attachments"
      required: true
  - type: checkboxes
      id: done
      attributes:
        label: "Definition of Done"
        description: "Check all that apply when the task is complete"
        options:
          - label: "Code implemented"
          - label: "Tests written and passing"
          - label: "Code reviewed and approved"
          - label: "Documentation updated"
          - label: "Merged into main branch"
