name: Task
description: "Create a task with status, priority, labels, linked issues, a user story, and DoD."
title: "[TASK]"
labels:
  - "task"
body:
  - type: markdown
    attributes:
      value: |
        Use this form to create a task. You can attach files or screenshots by dragging them into the "Description and attachments" field below.

  - type: input
    id: task_title
    attributes:
      label: "Task title"
      description: "Short, descriptive title for the task (this does not set the Issue title automatically)."
      placeholder: "Implement user login"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: "Status"
      description: "Current status of the task"
      options:
        - "To do"
        - "In progress"
        - "In review"
        - "Done"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Select the priority"
      options:
        - "P0 (Critical)"
        - "P1 (High)"
        - "P2 (Medium)"
        - "P3 (Low)"
    validations:
      required: true

  - type: checkboxes
    id: work_labels
    attributes:
      label: "Labels (informational)"
      description: "Select relevant areas. These do not auto-apply repo labels; use the sidebar after creating the issue."
      options:
        - label: "frontend"
        - label: "backend"
        - label: "bug"
        - label: "feature"
        - label: "testing"
        - label: "documentation"

  - type: input
    id: assignee_handles
    attributes:
      label: "Assignee GitHub handle(s)"
      description: "Optional. Example: @alice @bob"
      placeholder: "@username"

  - type: input
    id: linked_issues
    attributes:
      label: "Linked issues / Dependencies"
      description: "Mention related issues. Example: Depends on #12"
      placeholder: "Depends on #12"

  - type: textarea
    id: user_story
    attributes:
      label: "User story"
      description: "As a <user>, I want <goal>, so that <benefit>."
      placeholder: "As a TA, I want to upload a roster CSV so that students are added automatically."

  - type: dropdown
    id: sprint
    attributes:
      label: "Sprint"
      description: "Select which sprint this task belongs to"
      options:
        - "Sprint 1"
        - "Sprint 2"
        - "Sprint 3"
        - "Sprint 4"
        - "Backlog"

  - type: input
    id: due_date
    attributes:
      label: "Due date (optional)"
      description: "Enter an ISO date or milestone"
      placeholder: "2025-11-15"

  - type: textarea
    id: description
    attributes:
      label: "Description and attachments"
      description: "Detailed description, steps, acceptance criteria, logs, screenshots, or other files (drag & drop here)."
      placeholder: "Details, steps, acceptance criteria, screenshots/logs"
    validations:
      required: true

  - type: checkboxes
    id: dod
    attributes:
      label: "Definition of Done"
      description: "Check all that apply when the task is complete"
      options:
        - label: "Code implemented"
        - label: "Tests written and passing"
        - label: "Code reviewed and approved"
        - label: "Documentation updated"
        - label: "Merged into main branch"