name: Task
description: "Create a task with status, priority, labels, linked issues, a user story, and DoD."
title: "[TASK]"
labels:
  - "task"
body:
  - type: markdown
    attributes:
      value: |
        Use this form to create a task. You can attach files or screenshots by dragging them into the "Description and attachments" field below.

  - type: dropdown
    id: status
    attributes:
      label: "Status"
      description: "Current status of the task"
      options:
        - "To do"
        - "In progress"
        - "In review"
        - "Done"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Select the priority"
      options:
        - "P0 (Critical)"
        - "P1 (High)"
        - "P2 (Medium)"
        - "P3 (Low)"
    validations:
      required: true


  - type: textarea
    id: user_story
    attributes:
      label: "User story"
      description: "As a <user>, I want <goal>, so that <benefit>."
      placeholder: "As a TA, I want to upload a roster CSV so that students are added automatically."

  - type: dropdown
    id: sprint
    attributes:
      label: "Sprint"
      description: "Select which sprint this task belongs to"
      options:
        - "Sprint 1"
        - "Sprint 2"
        - "Sprint 3"
        - "Sprint 4"
        - "Backlog"

  - type: input
    id: due_date
    attributes:
      label: "Due date"
      description: "Enter an ISO date or milestone"
      placeholder: "2025-11-15"

  - type: textarea
    id: description
    attributes:
      label: "Description and attachments"
      description: "Detailed description, steps, acceptance criteria, logs, screenshots, or other files (drag & drop here)."
      placeholder: "Details, steps, acceptance criteria, screenshots/logs"
    validations:
      required: true
